config/routes.rb
Covers::Application.routes.draw do
  # Redirect http://pickura.com to http://www.pickura.com
  constraints(:host => /^pickura.com/) do
    root :to => redirect("http://www.pickura.com")
    match '/*path', :to => redirect {|params, req| "http://www.pickura.com/#{params[:path]}"}
  end

  match "/public/sitemap_index.xml.gz" => redirect("https://s3.amazonaws.com/pickura/sitemaps/sitemap_index.xml.gz"), :as => :sitemap_index


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos do
    member do
      post :watermark
    end
  end

  match 'categories(/:tags)'    => 'covers#index',          :as => :gallery
  match '/search/:query'        => 'covers#search',         :as => :search
  match '/:id'                  => 'covers#show',           :as => :gallery_show, :constraints => lambda{|req| req["id"].include? "facebook-timeline-cover" }
  match 'gallery/:sharing_url'  => 'covers#sharing_url',    :as => :gallery_sharing_url
  match 'most-popular'          => 'covers#most_popular',   :as => :gallery_popular
  match 'editors-pick'          => 'covers#editor_pick',    :as => :gallery_editor_pick
  match 'random'                => 'covers#random',         :as => :random
  match 'cover/:id/download'    => 'editor#download',       :as => :download_cover
  match 'cover/:id/upload'      => 'editor#upload',         :as => :upload_cover
  match 'cover/premium'         => 'covers#premium'
  match 'editor/:id'            => 'editor#show',           :as => :editor
  match 'pick'                  => 'facebook_photos#index', :as => :photo_picker
  post  'subscribe'             => 'home#subscribe',        :as => :subscribe
  post  'unsubscribe'           => 'home#unsubscribe',      :as => :unsubscribe

  get   'creator'               => 'creator#index'
  get   'creator/echo'          => 'creator#show'
  get  'creator/new'            => 'creator#new',           :as => :generate_cover
  get  'creator/:id'            => 'creator#show',          :as => :creator_cover
  root :to => 'home#index'
end

app/controllers/covers_controller.rb
class CoversController < ApplicationController
  def index
    @covers      = Photo.search(params)
    @tags        = Photo.relevant_tags
    @current_tag = params[:tags]
    @title = @current_tag.titleize if @current_tag
  end

  def search
    @covers = Photo.search_tank(params[:query], :page => params[:page], :per_page => params[:per_page])
    if @covers.count == 0
      # Most Popular
      @covers = Photo.search(:page => params[:page], :per_page => params[:per_page], :sorting => 'counter DESC, updated_at DESC, id DESC')
      @most_popular = true
      flash[:notice] = "Sorry, we couldn't find any covers for \"#{params[:query]}\", but maybe you like these :)"
    end
    @tags   = Photo.relevant_tags

    render :index
  end

  def most_popular
    @covers       = Photo.search(:page => params[:page], :per_page => params[:per_page], :sorting => 'counter DESC, updated_at DESC, id DESC')
    @tags         = Photo.relevant_tags
    @current_tag  = params[:tags]
    @most_popular = true
    @title = @current_tag.titleize if @current_tag

    render :index
  end

  def editor_pick
    @covers      = Photo.search(:page => params[:page], :per_page => params[:per_page], 
                    :tags => 'featured', :tag_type => :categories, :sorting => 'updated_at DESC, counter DESC, id DESC')

    @tags        = Photo.relevant_tags
    @current_tag = params[:tags]
    @editor_pick = true
    @title = @current_tag.titleize if @current_tag

    render :index
  end

  def random
    @covers = [Photo.random]
    14.times do |foo|
      @covers << Photo.random
    end
    @random = true
    @tags = Photo.relevant_tags

  end

  def sharing_url
    sharing_url = params[:sharing_url]      
    sharing_url =~ /^([-\d. ()]*)(.*)$/
    id = $1.to_i
    cover = Photo.find(id)
    # track redirects?
    redirect_to gallery_show_path(cover)
  end

  def show
    @cover = Photo.find(params[:id])
    @tags  = Photo.relevant_tags('count desc', 17)
    @title = @cover.name
    @cover.increase_view_count!
  end

  def creator
  end
end

app/views/covers/_tags.haml
.tag_list
  .tag_title Top Covers
  %ul.filters.tags
    %li.tag{:class => @most_popular? 'active' : ''}
      = link_to "Most Popular", gallery_popular_path, :title => "Most popular Facebook covers"
    %li.tag{:class => @editor_pick? 'active' : ''}
      = link_to "Editor's Pick", gallery_editor_pick_path, :title => "Our choices for your timeline"
    %li.tag{:class => @random? 'active' : ''}
      = link_to "Random Covers", random_path, :title => "Random images. Never get bored!"
      
  .tag_title Gallery Tags
  %ul.gallery_tags.tags
    - @tags.each do |tag|
      %li.tag{:class => (@current_tag == tag.name)? 'active' : ''}
        = link_to "#{tag.name.titleize}", gallery_path(tag.name), :title => "#{tag.name.titleize} Facebook covers"
        %span.label= tag.count

app/views/covers/index.haml
- content_for :meta do
  %meta{:name => "description", :content => "Description: Get creative. get designer. get Pickura. The only designer Facebook Timeline cover editor around, Tags: #{@tags.all.join(" ")}"}
- content_for :javascripts do
  = javascript_include_tag "http://w.sharethis.com/button/buttons.js"
  :javascript
    stLight.options({publisher: "30b4a467-2713-47a7-91af-93a3e3a6343a", publisherGA:"UA-29696639-1"});

.row
  .span3
    = render 'tags'
  .span9
    .gallery_list
      - @covers.each do |cover|
        .photo
          .name= cover.name
          .download_count
            <i class="icon-download"></i>
            =cover.download_count
            Downloads
          .img
            - cover_tags = cover.tags.empty? ? '' : cover.tags.join(' ')
            - cover_description = "#{cover.name} - #{cover_tags}"
            = link_to image_tag(cover.source.preview, :class => 'cover', :alt => cover_description), gallery_show_path(cover)
          .hide.social_sharing
            .content
              %span.st_twitter_hcount{:displayText=>'Tweet', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}
              %span.st_facebook_hcount{:displayText=>'Facebook', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}
              %span.st_plusone_hcount{:displayText=>'Google +1', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}
              %span.st_pinterest_hcount{:displayText=>'Pinterest', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}

.row
  .span9.offset3
    .flickr_pagination
      = will_paginate @covers, :container => false
      .page_info
        = page_entries_info @covers

app/views/covers/random.haml
- content_for :meta do
  %meta{:name => "description", :content => "Description: Get creative. get designer. get Pickura. The only designer Facebook Timeline cover editor around, Tags: #{@tags.all.join(" ")}"}
- content_for :javascripts do
  = javascript_include_tag "http://w.sharethis.com/button/buttons.js"
  :javascript
    stLight.options({publisher: "30b4a467-2713-47a7-91af-93a3e3a6343a", publisherGA:"UA-29696639-1"});

.row
  .span3
    = render 'tags'
  .span9
    .gallery_list
      - @covers.each do |cover|
        .photo
          .name= cover.name
          .download_count
            <i class="icon-download"></i>
            =cover.download_count
            Downloads
          .img
            - cover_tags = cover.tags.empty? ? '' : cover.tags.join(' ')
            - cover_description = "#{cover.name} - #{cover_tags}"
            = link_to image_tag(cover.source.preview, :class => 'cover', :alt => cover_description), gallery_show_path(cover)
          .hide.social_sharing
            .content
              %span.st_twitter_hcount{:displayText=>'Tweet', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}
              %span.st_facebook_hcount{:displayText=>'Facebook', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}
              %span.st_plusone_hcount{:displayText=>'Google +1', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}
              %span.st_pinterest_hcount{:displayText=>'Pinterest', :st_url=>permalink(cover), :st_title => cover.name, :st_summary => cover_description}

.row
  .span9.offset3
    %a.btn.btn-primary.btn-large{:href => random_path, :style => "margin-bottom: 40px;margin-top: 20px;width: 666px;height: 19px;"} Show me More Covers!

app/views/covers/show.haml
- content_for(:meta) do
  %meta{:name => "description", :content => "Name: #{@cover.name}, Tags: #{@cover.tag_list.join(" ")}"}
- content_for :javascripts do
  = javascript_include_tag "http://w.sharethis.com/button/buttons.js"
  :javascript
    stLight.options({publisher: "ur-cea037fd-e637-a2ad-7782-f86cf3376519"});
    
.row
  .span9.pull-right.show_cover
    .gallery_list
      .photo
        .row
          .span4
            %h1= @cover.name
          .span2.pull-right{:style => "text-align: right;"}
            %i.icon-download
            = @cover.download_count
            Downloads
        .row
          .span9
            - photo_tags = @cover.tags.empty? ? '' : @cover.tags.join(' ')
            - cover_description = "#{@cover.name} - #{photo_tags}"
            = image_tag(@cover.source.preview, :alt => cover_description)
        - if !@cover.description.nil?
          .row
            .span8.description
              = "‟#{@cover.description}”"
        .row
          .span8.pull-right
            = render :partial => 'editor/actions'

    .social_sharing    
      %h3{:style => "margin-bottom:11px"}="Share this cover with your friends"
      %span.st_twitter_hcount{:displayText=>'Tweet', :st_url => permalink(@cover), :st_title => @cover.name, :st_summary => cover_description}
      %span.st_facebook_hcount{:displayText=>'Facebook', :st_url => permalink(@cover), :st_title => @cover.name, :st_summary => cover_description}
      %span.st_plusone_hcount{:displayText=>'Google +1', :st_url => permalink(@cover), :st_title => @cover.name, :st_summary => cover_description}
      %span.st_pinterest_hcount{:displayText=>'Pinterest', :st_url => permalink(@cover), :st_title => @cover.name, :st_summary => cover_description}
    .facebook
      .fb-comments{"data-href"=>permalink(@cover), "data-num-posts"=>"2", "data-width"=>"668", "data-colorscheme"=>"dark"}
  .span3.pull-left
    = render 'tags'

#generating_modal.modal.hide
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h2 Generating
  .modal-body
    .row-fluid
      .msg.span8
        %p We are currently generating your new custom cover
        %p In the meantime, why not Like us on Facebook?
        .upload-bar{:style => "text-align:center"}
          = image_tag 'loading30.gif'
      .modal-right.span4
        %h3 Like us:
        .fb-widget
          .fb-like{"data-href"=> "http://www.pickura.com","data-send"=>"false", "data-width"=>"100", 'data-layout' => 'box_count', "data-show-faces"=>"false", "data-font"=>"lucida grande"}