config/routes.rb
Covers::Application.routes.draw do
  # Redirect http://pickura.com to http://www.pickura.com
  constraints(:host => /^pickura.com/) do
    root :to => redirect("http://www.pickura.com")
    match '/*path', :to => redirect {|params, req| "http://www.pickura.com/#{params[:path]}"}
  end

  match "/public/sitemap_index.xml.gz" => redirect("https://s3.amazonaws.com/pickura/sitemaps/sitemap_index.xml.gz"), :as => :sitemap_index


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos do
    member do
      post :watermark
    end
  end

  match 'categories(/:tags)'    => 'covers#index',          :as => :gallery
  match '/search/:query'        => 'covers#search',         :as => :search
  match '/:id'                  => 'covers#show',           :as => :gallery_show, :constraints => lambda{|req| req["id"].include? "facebook-timeline-cover" }
  match 'gallery/:sharing_url'  => 'covers#sharing_url',    :as => :gallery_sharing_url
  match 'most-popular'          => 'covers#most_popular',   :as => :gallery_popular
  match 'editors-pick'          => 'covers#editor_pick',    :as => :gallery_editor_pick
  match 'random'                => 'covers#random',         :as => :random
  match 'cover/:id/download'    => 'editor#download',       :as => :download_cover
  match 'cover/:id/upload'      => 'editor#upload',         :as => :upload_cover
  match 'cover/premium'         => 'covers#premium'
  match 'editor/:id'            => 'editor#show',           :as => :editor
  match 'pick'                  => 'facebook_photos#index', :as => :photo_picker
  post  'subscribe'             => 'home#subscribe',        :as => :subscribe
  post  'unsubscribe'           => 'home#unsubscribe',      :as => :unsubscribe

  get   'creator'               => 'creator#index'
  get   'creator/echo'          => 'creator#show'
  get  'creator/new'            => 'creator#new',           :as => :generate_cover
  get  'creator/:id'            => 'creator#show',          :as => :creator_cover
  root :to => 'home#index'
end

app/views/shared/_countdown.haml
.alert.fade.in#countdown{:style => "margin-left:10px"}
  %a.close{:href =>"#", "data-dismiss" => "alert"} &times;
  %strong{:style => "line-height: 28px; font-size: 21px;"} New Features Added Weekly!
  .pull-right
    %button{"data-toggle"=>"modal", :href=>"#mailModal", :style => "vertical-align:top", :class =>"btn btn-success", :id => "mailModalBtn"}
      %i.icon-envelope.icon-white
      %span.text
        Notify me on this Update!
    %a{:href=>"https://twitter.com/pickura",:class=>"twitter-follow-button","data-show-count"=>"false","data-size"=>"large"}Follow @pickura
  %br
  Next update in
  #time{:style => "display:inline; line-height: 27px; margin-right:12px"}

app/views/shared/_menu.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.i-bar
        %span.i-bar
        %span.i-bar
      %a.brand{:href => "/", :style => "padding-bottom:9px"}= image_tag("logo.png")
      .container.nav-collapse
        %ul.nav
          %li= link_to "Gallery",       gallery_path
          %li= link_to "Most Popular",  gallery_popular_path
          %li= link_to "Editor's pick", gallery_editor_pick_path
          %li= link_to "Templates",     creator_path

        %ul.nav.pull-right
          %li
            .navbar-search.pull-left#search-form
              = text_field_tag(:query, nil,{:class=> "search-query span2", :placeholder=>"Search", :id => "query"})

          - if user_signed_in?
            %li= link_to 'Sign out', destroy_user_session_path, :method => :delete, :style => "font-weight:bold;"
            %li{:style => "height:40px"}= image_tag(current_user.avatar.thumb.url)
          - elsif @current_controller != "home"
            %li
              .menu_facebook
                = link_to (image_tag "fb_login.png"), user_omniauth_authorize_path(:facebook)

app/views/shared/_subscribe_form.haml
.modal#mailModal.hide.fade
  = form_tag subscribe_path, :remote => true, :id => "emailForm" do
    .modal-header
      %a{:class=>"close", "data-dismiss"=>"modal"}×
      %h3 Automatic Update Notification
    .modal-body
      .control-group
        .controls
          .input-prepend
            %span{:class=>"add-on"}
              %i{:class=>"icon-envelope"}
            %input{:class=>"span3", :id=>"inputIcon", :type=>"text", :name => "email", :placeholder => "E.g. user@pickura.com"}
            %span.help-inline
            %span.note
              *And don't worry, we also hate spam :)
    .modal-footer
      %button{:href=>"#", :class => "btn btn-primary", :id => "emailBtn"} Sign Up
      %a{"data-toggle"=>"modal", :href=>"#mailModal", :class => "btn"} Cancel