config/routes.rb
Covers::Application.routes.draw do
  # Redirect http://pickura.com to http://www.pickura.com
  constraints(:host => /^pickura.com/) do
    root :to => redirect("http://www.pickura.com")
    match '/*path', :to => redirect {|params, req| "http://www.pickura.com/#{params[:path]}"}
  end

  match "/public/sitemap_index.xml.gz" => redirect("https://s3.amazonaws.com/pickura/sitemaps/sitemap_index.xml.gz"), :as => :sitemap_index


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos do
    member do
      post :watermark
    end
  end

  match 'categories(/:tags)'    => 'covers#index',          :as => :gallery
  match '/search/:query'        => 'covers#search',         :as => :search
  match '/:id'                  => 'covers#show',           :as => :gallery_show, :constraints => lambda{|req| req["id"].include? "facebook-timeline-cover" }
  match 'gallery/:sharing_url'  => 'covers#sharing_url',    :as => :gallery_sharing_url
  match 'most-popular'          => 'covers#most_popular',   :as => :gallery_popular
  match 'editors-pick'          => 'covers#editor_pick',    :as => :gallery_editor_pick
  match 'random'                => 'covers#random',         :as => :random
  match 'cover/:id/download'    => 'editor#download',       :as => :download_cover
  match 'cover/:id/upload'      => 'editor#upload',         :as => :upload_cover
  match 'cover/premium'         => 'covers#premium'
  match 'editor/:id'            => 'editor#show',           :as => :editor
  match 'pick'                  => 'facebook_photos#index', :as => :photo_picker
  post  'subscribe'             => 'home#subscribe',        :as => :subscribe
  post  'unsubscribe'           => 'home#unsubscribe',      :as => :unsubscribe

  get   'creator'               => 'creator#index'
  get   'creator/echo'          => 'creator#show'
  get  'creator/new'            => 'creator#new',           :as => :generate_cover
  get  'creator/:id'            => 'creator#show',          :as => :creator_cover
  root :to => 'home#index'
end

app/controllers/editor_controller.rb
class EditorController < ApplicationController
  before_filter :find_cover

  def show
  end

  def download
    #redirect_to @cover.source.branded.url, :type => 'image/jpeg'
    @cover.increase_download_count!
    file = open(@cover.source.branded.url)
    send_file file, :type => 'image/jpeg', :filename => File.basename(@cover.source.url)
  end

  def upload
    Facebook.upload_cover(@cover, current_user)
  end

  def find_cover
    if params[:custom_cover_id]
      @cover = CustomCover.find(params[:custom_cover_id])
    else
      @cover = Photo.find(params[:id])
    end
  end
end

app/views/editor/_actions.haml
- if !user_signed_in?
  .actions
    %a#download_button.btn.btn-primary.btn-large{:href => "#{user_omniauth_authorize_path(:facebook)}", 'data-loading-text' => 'Authenticating with Facebook...'}
      %i{:class => "icon-picture icon-white"}
      Preview with our new Template


    %a#download_button.btn.btn-primary.btn-large{:href => "#{user_omniauth_authorize_path(:facebook)}", 'data-loading-text' => 'Authenticating with Facebook...'}
      %i{:class => "icon-download-alt icon-white"}
      Download
      
    %a#upload_button.btn.btn-primary.btn-large{:href => "#{user_omniauth_authorize_path(:facebook)}", 'data-loading-text' => 'Authenticating with Facebook...'}
      %i{:class => "icon-upload icon-white"}
      Upload to Facebook

- else
  .actions
    -#/ = link_to 'Customize', editor_path(@cover), :class => 'btn btn-info btn-large'
    %a#download_button.btn.btn-primary.btn-large{:href => generate_cover_path(:model => :echo, :background => @cover.id), 'data-loading-text' => 'Authenticating with Facebook...', :class => 'generate-link'}
      %i{:class => "icon-picture icon-white"}
      Preview with our new Template
    %a#download_button.btn.btn-primary.btn-large{:href => "#{download_cover_url}", 'data-loading-text' => 'Downloading...'}
      %i{:class => "icon-download-alt icon-white"}
      Download
    %a#upload_button.btn.btn-primary.btn-large{:href => '#upload_modal', 'data-loading-text' => 'Uploading...', 'data-toggle' => 'modal'}
      %i{:class => "icon-upload icon-white"}
      Upload to Facebook
  
  #upload_modal.modal.hide
    .modal-header
      %a.close{'data-dismiss' => 'modal'} x
      .step1
        %h2 Uploading Cover...
      .step2
        %h2 Your cover is ready to use!
    .modal-body
      .step1.row-fluid
        .msg.span8
          %p We are currently uploading your new Facebook Cover
          %p In the meantime, why not Like us on Facebook?
          .upload-bar
            = image_tag 'loading30.gif'
        .modal-right.span4
          %h3 Like us:
          .fb-widget
            .fb-like{"data-href"=> "http://www.pickura.com","data-send"=>"false", "data-width"=>"100", 'data-layout' => 'box_count', "data-show-faces"=>"false", "data-font"=>"lucida grande"}
        = link_to 'Upload', upload_cover_path(@cover), :class => 'trigger', :remote => true, :style => 'display:none'
      .step2
        %p Now set the cover on your profile in Facebook. Click the <strong>"Change my cover"</strong> button and follow the steps below to set your new cover on your profile:
        .button-out
          = link_to 'Change my cover', 'http://www.facebook.com/me', :target => '_blank', :class => 'btn btn-info btn-large'
        .instructions
          = image_tag 'cover-instructions.png'

app/views/editor/_editor_sidebar.haml
.row.photo-list.photo-select-bar
  - 4.times do |i|
    .photo-select{:id => "box_#{i}"}
      = link_to 'Choose a photo', photo_picker_path(:box => i), :remote => true, :class => 'thumb'
#fb_photo_picker

app/views/editor/_toolbar.haml
.form-actions#stickers 
  - Sticker.all.each do |sticker|
    = image_tag sticker, :class => 'sticker'
.well
  = link_to "Save", '#', :class => 'btn'

app/views/editor/show.haml
.editor
  #canvas
    .cover_image#screen
      = image_tag @cover.source.branded.url, :id => 'user_image', :style => "z-index:10"
  
    .profile_pic_wrapper
      .profile_pic
        .image
          = image_tag current_user.avatar.url, :id => 'user_avatar'#, :height => 125, :width => 125
      
  = render :partial => 'editor_sidebar'
  = #render :partial => 'actions'

app/views/editor/upload.js.erb
$('#upload_modal').addClass('uploaded');