config/routes.rb
Covers::Application.routes.draw do
  # Redirect http://pickura.com to http://www.pickura.com
  constraints(:host => /^pickura.com/) do
    root :to => redirect("http://www.pickura.com")
    match '/*path', :to => redirect {|params, req| "http://www.pickura.com/#{params[:path]}"}
  end

  match "/public/sitemap_index.xml.gz" => redirect("https://s3.amazonaws.com/pickura/sitemaps/sitemap_index.xml.gz"), :as => :sitemap_index


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos do
    member do
      post :watermark
    end
  end

  match 'categories(/:tags)'    => 'covers#index',          :as => :gallery
  match '/search/:query'        => 'covers#search',         :as => :search
  match '/:id'                  => 'covers#show',           :as => :gallery_show, :constraints => lambda{|req| req["id"].include? "facebook-timeline-cover" }
  match 'gallery/:sharing_url'  => 'covers#sharing_url',    :as => :gallery_sharing_url
  match 'most-popular'          => 'covers#most_popular',   :as => :gallery_popular
  match 'editors-pick'          => 'covers#editor_pick',    :as => :gallery_editor_pick
  match 'random'                => 'covers#random',         :as => :random
  match 'cover/:id/download'    => 'editor#download',       :as => :download_cover
  match 'cover/:id/upload'      => 'editor#upload',         :as => :upload_cover
  match 'cover/premium'         => 'covers#premium'
  match 'editor/:id'            => 'editor#show',           :as => :editor
  match 'pick'                  => 'facebook_photos#index', :as => :photo_picker
  post  'subscribe'             => 'home#subscribe',        :as => :subscribe
  post  'unsubscribe'           => 'home#unsubscribe',      :as => :unsubscribe

  get   'creator'               => 'creator#index'
  get   'creator/echo'          => 'creator#show'
  get  'creator/new'            => 'creator#new',           :as => :generate_cover
  get  'creator/:id'            => 'creator#show',          :as => :creator_cover
  root :to => 'home#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :source, PhotoUploader
  acts_as_taggable
  acts_as_taggable_on :categories

  include Tanker # Search engine

  extend FriendlyId
  friendly_id :name_suffix, use: :slugged
  def name_suffix
    "#{name}-facebook-timeline-cover"
  end

  before_validation :default_watermark
  before_save       :recreate_watermark
  after_save        :expire_cache, :update_tank_indexes
  after_destroy     :expire_cache, :delete_tank_indexes

  WM_POSITIONS = {:south_east => 'Bottom Right', :north_east => 'Top Right', :north_west => 'Top Left', :south_west => 'Bottom Left'}

  tankit 'photo_index' do
    indexes :name
    indexes :description
    indexes :id
    indexes :tag_list     # Array of Tags
    indexes :counter
    indexes :counter_downloads
  end

  # Note! Will Paginate pagination, thanks mislav!
  def self.per_page
    15
  end

  # Returns a collection of tags (with memcached)
  #  [page            Integer       Page number of the collection
  #  [per_page]       Integer       Number of elements per page
  #  [tags]           String/Array  Tags to search
  #  [sorting]        String        Column to sort the collection
  #  [search_by_tag]  Boolean       If true it will search on :tags, otherwise on :categories
  def self.search(opts = {})
    opts[:page]     ||= 1
    opts[:per_page] ||= 15
    opts[:sorting]  ||= 'id DESC'
    opts[:tag_type] ||= :tags
    
    if opts[:tags]
      result = Photo.tagged_with(opts[:tags], :on => opts[:tag_type])
    else
      result = Photo
    end
    
    result.order(opts[:sorting]).paginate(:page => opts[:page], :per_page => opts[:per_page])
  end

  # Returns a collection of tags (with memcached)
  def self.relevant_tags(order = 'count desc', limit = nil)
    Photo.tag_counts(:order => order, :at_least => 10, :limit => limit)
  end

  def move_watermark(corner = nil)
    self.watermark_position = corner
    self.save
  end

  def default_watermark
    self.watermark_position ||= 'south_east'
  end

  def recreate_watermark
    if !self.new_record? && self.watermark_position_changed?
      self.source.recreate_versions!
    end
  end

  def increase_view_count!
    ActiveRecord::Base.transaction do
      self.counter = self.counter + 1
      self.save!
    end
  end

  def increase_download_count!
    ActiveRecord::Base.transaction do
      self.counter_downloads = self.counter_downloads + 1
      self.save!
    end
  end

  def download_count
    count = counter_downloads + download_seed_fake
  end

  def self.random
    offset = rand(Photo.count)
    rand_record = Photo.first(:offset => offset)
  end
  
  protected

  def expire_cache
    Rails.cache.clear
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout 'admin'
  before_filter :security_check

  ##########################################################################################
  # ADMIN CONTROLLER ACTIONS BELLOW
  ##########################################################################################
  def index
    @photos = Photo.search(:page => params[:page], :per_page => 50, :sorting => 'id ASC')
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def watermark
    @photo = Photo.find(params[:id])
    if @photo.move_watermark(params[:corner])
      redirect_to @photo, notice: 'Photo successfully updated.'
    else
      redirect_to @photo, notice: 'Error'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.js { render :layout => false }
    end
  end

private

  def security_check
    if !user_signed_in? || !current_user.admin?
      flash[:notice] = "Sorry, you are not authorized there :)"
      redirect_to root_url
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def watermark_positions_options
    Photo::WM_POSITIONS.collect{|k, v| [k.to_s, v]}
  end
  
  def permalink(cover)
    if Rails.env.production?
      "http://www.pickura.com/gallery/#{cover.id}-#{cover.slug}"
    else
      "http://#{request.host}:#{request.port}/gallery/#{cover.id}-#{cover.slug}"
    end
  end

end

app/views/photos/_form.html.haml
= form_for @photo, :html => {:multipart => true} do |f|
  -if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
    
  .field
    = f.label :source
    = f.file_field :source
    
  .field
    = f.label :Tags
    = f.text_field :tag_list

  .field
    = f.label :Categories
    = f.text_field :category_list

  .field
    = f.label :Description
    = f.text_area(:description, :cols => 100, :rows => 6)

  .actions
    = f.submit 'Save'

app/views/photos/destroy.js.erb
remove_photo(<%= dom_id(@photo) %>);

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/gallery.haml
.row.span11.title_bar
  .title Cover Photos

.row-fluid.span10.offset1
  .tag_list.span2
    .tag_title Tag List
    %ul.unstyled.tags
      - @tags.each do |tag|
        %li.tag{:class => (@current_tag == tag.name)? 'active' : ''}
          = link_to "#{tag.name.capitalize}", gallery_path(tag.name), {:style => "margin-right:-25px; font-weight: bold"}
          %span.label{:style => "float:right; margin-right:10px"}= tag.count

  .gallery_list.span9
    - @photos.each do |photo|
      .row
        .photo.span9
          .name= photo.name
          .img
            = link_to image_tag(photo.source.branded), editor_path(photo)
          .hide.fb_comments
            .fb-like{"data-href"=> "#{seo_photo_path(photo)}","data-send"=>"true", "data-width"=>"450", "data-show-faces"=>"false", "data-colorscheme"=>"dark", "data-font"=>"lucida grande"}
            .span{:style => "float:right"}= link_to "view image", seo_photo_path(photo)
          

.span10
  .flickr_pagination
    = will_paginate @photos, :container => false
    .page_info
      = page_entries_info @posts

app/views/photos/gallery_show.haml
.row.span11.title_bar
  .title Cover Photos

.row-fluid.span10.offset1
  .tag_list.span2
    .tag_title Tag List
    %ul.unstyled.tags
      - @tags.each do |tag|
        %li.tag{:class => (@current_tag == tag.name)? 'active' : ''}
          = link_to "#{tag.name.capitalize}", gallery_path(tag.name), {:style => "margin-right:-25px; font-weight: bold"}
          %span.label{:style => "float:right; margin-right:10px"}= tag.count

  .gallery_list.span9
    .row
      .photo.span9
        .name= @photo.name
        .img
          = link_to image_tag(@photo.source.branded), editor_path(@photo)
        .fb_comments2
          .fb-like{"data-send"=>"true", "data-width"=>"450", "data-show-faces"=>"false", "data-colorscheme"=>"dark", "data-font"=>"lucida grande"}
    .row
      .photo.span9
        .fb-comments{"data-href"=>"#{seo_photo_path(@photo)}", "data-num-posts"=>"2", "data-width"=>"668", "data-colorscheme"=>"dark"}

app/views/photos/index.html.haml
.row
  .span10.title_admin Listing photos
  .span2.new_photo_link= link_to "Add Photo", new_photo_path, {:class => "btn btn-primary"}

  %br
  %br
  .flickr_pagination_admin
    = will_paginate @photos, :container => false
  %br  
.row
  %ul.photo_list
    - @photos.each do |photo|
      %li.photo{:id => dom_id(photo)}
        .img
          = link_to photo.source.branded.url, :rel => "prettyPhoto[pp_gal]", :title => "#{photo.name}" do
            = image_tag photo.source.thumb, :size => "260x96"
        .name
          = best_in_place photo, :name
        .tags
          %b= "Tags: " unless photo.tag_list.blank?
          = best_in_place photo, :tag_list, {:nil => "click to add tags"}
        .category
          %b= "Categories: " unless photo.category_list.blank?
          = best_in_place photo, :category_list, {:nil => "click to add categories"}
        .description
          = truncate(photo.description, :length => 70, :omission => '... (more)')
        .downloads
          Downloads:
          = best_in_place photo, :download_seed_fake, {:nil => "click to modify the downloads fake base", :html_attrs => {:size => 10}}


        .watermark
          = label :photo_watermark_position, 'Watermark:'
          = best_in_place photo, :watermark_position, :type => :select, :collection => watermark_positions_options
        .edit_photo
          = link_to edit_photo_path(photo) do
            .btn.btn-info Edit Photo
        .delete= link_to '(Delete)',  photo_url(photo), {:remote => true, :method => :delete}

  %br
  .flickr_pagination_admin
    = will_paginate @photos, :container => false
    .page_info
      = page_entries_info @posts

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice

%h1= @photo.name

= image_tag @photo.source.url(:branded)

%p
  %b Tags
  = @photo.tag_list
  
%p
  %b Categories
  = @photo.category_list

%p
  %b Description
  = @photo.description

%p
  %b Watermark
.waterMarkPosition
  - if false 
    = form_for @photo, :url => watermark_photo_path, :method => :post do |f|
      = f.select :watermark_position, watermark_positions_options
      = f.submit :move
.topButtons
  = button_to 'TopLeft', watermark_photo_path(:corner => :north_west), :method => :post
  = button_to 'TopRight', watermark_photo_path(:corner => :north_east), :method => :post
.bottomButtons
  = button_to 'BottomLeft', watermark_photo_path(:corner => :south_west), :method => :post
  = button_to 'BottomRight', watermark_photo_path(:corner => :south_east), :method => :post

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path